language: node_js
node_js:
  - '8'
dist: trusty
sudo: false
cache:
  directories:
    - node_modules
addons:
  chrome: stable

before_script:
  - npm install -g firebase-tools
  - cp functions/src/config/config.json src/config/config.json
script:
  - npm run build

before_deploy:
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - export REACT_APP_BRANCH=$(if [ "$TRAVIS_BRANCH" == "production" ]; then echo "PRODUCTION"; else echo "STAGING"; fi)
  - echo "REACT_APP_BRANCH=$REACT_APP_BRANCH"
  - export FIREBASE_TOKEN=$(if [ "$TRAVIS_BRANCH" == "production" ]; then echo "$FIREBASE_PRODUCTION_TOKEN"; else echo "$FIREBASE_STAGING_TOKEN"; fi)
deploy:
  - provider: script
    script: firebase use default && firebase deploy --only hosting
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: firebase use production && firebase deploy --only hosting
    skip_cleanup: true
    on:
      branch: production
after_deploy:
  - echo "REACT_APP_BRANCH=$REACT_APP_BRANCH"
