language: node_js
node_js:
  - '8'
dist: trusty
sudo: false
cache:
  directories:
    - node_modules
addons:
  chrome: stable
before_script:
  - npm install -g firebase-tools
script:
  - npm run build
before_deploy:
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - export REACT_APP_BRANCH=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "PRODUCTION"; else echo "STAGING"; fi)
  - echo "REACT_APP_BRANCH=$REACT_APP_BRANCH"
deploy:
  - provider: script
    script:
      - firebase use default
      - echo "Deploying to dev server"
      - firebase deploy --token $FIREBASE_STAGING_TOKEN --only hosting:dev
    skip_cleanup: true
    on:
      branch: dev
  - provider: script
    script:
      - firebase deploy --token $FIREBASE_PRODUCTION_TOKEN --only hosting:prod
    skip_cleanup: true
    on:
      branch: master
after_deploy:
  - echo "REACT_APP_BRANCH=$REACT_APP_BRANCH"
