language: node_js
node_js:
  - '8'
dist: trusty
sudo: false
cache:
  directories:
    - node_modules
addons:
  chrome: stable
before_script:
  - npm install -g firebase-tools
script:
  - npm run build
deploy:
  - provider: firebase
    skip_cleanup: true
    token: '$FIREBASE_STAGING_TOKEN'
    message: Firebase staging deploy success
    project: precious-plastics-v4-dev
    script: env REACT_APP_FIREBASE_PROD_CONFIG='{"apiKey":"AIzaSyChVNSMiYxCkbGd9C95aChr9GxRJtW6NRA","authDomain":"precious-plastics-v4-dev.firebaseapp.com","databaseURL":"https://precious-plastics-v4-dev.firebaseio.com","messagingSenderId":"174193431763","projectId":"precious-plastics-v4-dev","storageBucket":"precious-plastics-v4-dev.appspot.com"}'
    on:
      branch: dev
  - provider: firebase
    skip_cleanup: true
    token: '$FIREBASE_PRODUCTION_TOKEN'
    message: Firebase production deploy success
    project: onearmyworld
    on:
      branch: master
