# Full list of config options:
# https://cloud.google.com/appengine/docs/standard/nodejs/config/appref
runtime: nodejs8
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
automatic_scaling:
  max_instances: 1
